Feature
Knhn0/coffeeTerminal pull request #2
Opened 2022-12-11 10:40 UTC by Knhn0

2022-12-11 23:22 UTC, Eg0rS requested changes

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Interfaces/IOrderRepository.cs
> +    Task<Order> GetOrderByName(string name);
брать заказ по названию такая себе идея, тк заказы могут быть названы одинаково, как доп метод к взятию заказа по id норм,

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Interfaces/IUserRepository.cs
> +    Task<User> GetUserByName(string name);
с юзером тоже самое, тут должны быть все crud методы

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Migrations/20221127203551_Initial.cs
> +                    Password = table.Column<string>(type: "text", nullable: false)
надеюсь тут лежит хеш а не строка

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Migrations/20221127203551_Initial.cs
> +                    ExpirationData = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
тут надеюсь для времени ты используешь datetimeoffset, а не обычный

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Migrations/20221127203551_Initial.cs
> +                    ExpirationData = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
иначе сдвиг на 3 часа идет нахуй

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Repositories/CoffeeRepository.cs
> +        await _db.Goods.AddAsync(entity);
собери все такски в 1 и сделай whenall(tasks); зачем ты последовательно ждешь 2 асинхронные операции

2022-12-11 23:22 UTC, Eg0rS commented on CoffeeTerminal.DAL/Repositories/OrderRepository.cs
> +        await _db.Orders.AddAsync(entity);
тут тоже

2022-12-13 05:47 UTC, Knhn0 commented on CoffeeTerminal.DAL/Interfaces/IOrderRepository.cs
> +    Task<Order> GetOrderByName(string name);
Исправил, оставил id

2022-12-13 05:56 UTC, Knhn0 commented on CoffeeTerminal.DAL/Interfaces/IUserRepository.cs
> +    Task<User> GetUserByName(string name);
добавил crud

2022-12-13 05:59 UTC, Knhn0 commented on CoffeeTerminal.DAL/Migrations/20221127203551_Initial.cs
> +                    ExpirationData = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
fixed

2022-12-15 13:58 UTC, merged